@startuml classes

class exercice1.hpp{
    SDL initialisation
    Renderer initialisation
    texture initialisation
    ---
    public
    MainSDLWindow
    ~MainSDLWindow
    {static} int Init
    ---
    private
    {static} SDL_window *window
    {static} SDL_window *renderer
}

class exercice1.cpp{
    MainSDLWindow
    this window = NULL
    this renderer = NULL
    ---
    ~MainSDLWindow
    SDL_DestroyRenderer
    SDL_DestroyWindow
    SDL_Quit
    ---
    Init
    SDL part;
    Window part;
    Renderer part;
    
    ---
    {static} int main(void)
    MainSDLWindow main_window
    main_window.init()
    return 0

}

@enduml