@startuml classes

class exercice1hpp{
    SDL initialisation
    Renderer initialisation
    texture initialisation
    ---
    +public :
    Window
    (destructor)Window
    {static} int Init
    ---
    __private__
    {static} SDL_window *window
    {static} SDL_window *renderer
}
exercice1cpp *--  exercice1hpp : define
class exercice1cpp{
    +Window
    this window = NULL
    this renderer = NULL
    ---
    (desctructor)Window
    -SDL_DestroyRenderer
    -SDL_DestroyWindow
    -SDL_Quit
    ---
    +Init(const char* nameWindow, int posX, int posY, int rendererW, int rendererH, bool fullscreen)
    SDL avoid errors;
    Creating the Window ;
    Creating Renderer ;
    
    ---
    {static} int main(void)
    Window main_window
    main_window.init()
    return 0

}

@enduml
